version: "3.7"

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: employee_directory
      MYSQL_USER: vinay # Root username
      MYSQL_PASSWORD: 123456 # Root password
    ports:
      - "3310:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mynetwork

  app:
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/employee_directory
      MYSQL_HOST: mysql
      MYSQL_DATABASE: employee_directory
      MYSQL_USER: vinay # Replace with the username you want for a regular user
      MYSQL_PASSWORD: 123456 # Replace with the password for the regular user
    networks:
      - mynetwork

volumes:
  mysql_data:

networks:
  mynetwork:
    driver: bridge
