apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: MTIzNDU2 # Base64 encoded value of '123456'
  mysql-database: ZW1wbG95ZWVfZGlyZWN0b3J5 # Base64 encoded value of 'employee_directory'
  mysql-user: dmluYXk= # Base64 encoded value of 'vinay'
  mysql-password: MTIzNDU2 # Base64 encoded value of '123456'
